upstream saltai_cloud_api {
    server api:8000;
}

upstream saltai_cloud_miniapp {
    server miniapp:80;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 64m;

    location = / {
        return 302 /miniapp/;
    }

    location = /miniapp {
        return 301 /miniapp/;
    }

    location /miniapp/ {
        proxy_pass http://saltai_cloud_miniapp;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v1/ {
        proxy_pass http://saltai_cloud_api;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}